name: CI SAMYPlugin-CPP-Template Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: create and move to build folder
      run: mkdir build && cd build
    - name: run cmake
      run: cmake ..
    - name: run make
      run: make
    - name: make distcheck
      run: make distcheck
    
      
  tests:
    needs: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout SAMYCore repository
      uses: actions/checkout@v2
      with:
        repository: FHTW/SAMYCore
        token: ${{ secrets.GIT_HUB_TOKEN }} # stored in GitHub secrets
        path: .github/actions/my-action
    - name: Run SAMYCore in test mode
      uses: ./.github/actions/run_SAMYCore_test

    - name: Run SAMYCore in test mode
      uses: ./.github/actions/run_SAMYCore_test
        
    - name: create and move to build folder
      run: mkdir build && cd build
    - name: run cmake
      run: cmake ..
    - name: run make
      run: make
    - name: make distcheck
      run: make distcheck


  dockerization:
    needs: [ build, tests ]
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
    - name: create and move to build folder
      run: mkdir build && cd build
    - name: run cmake
      run: cmake ..
    - name: run make
      run: make
    - name: make distcheck
      run: make distcheck
