name: Linux Build

on: push #[push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y -qq libboost-python1.71.0 build-essential cmake libyaml-cpp-dev libboost-all-dev git libspdlog-dev
    - name: "Build open63541"
      uses: .github/actions/build_linux.yaml@v1
      with:
        built_type: build_open62541
    - name: Build
      uses: .github/actions/build_linux.yaml@v1
      with:
        built_type: build_release


# name: Linux Build
#
# on: push #[push, pull_request]
# jobs:
#   build:
#     strategy:
#       fail-fast: false
#       matrix:
#         include:
#           - build_name: "Build open62541"
#             cmd_deps: sudo apt-get install -y -qq libboost-python1.71.0 build-essential cmake libyaml-cpp-dev libboost-all-dev git libspdlog-dev
#             cmd_action: build_open62541
#           - build_name: "Release Build"
#             cmd_deps: sudo apt-get install -y -qq libboost-python1.71.0 build-essential cmake libyaml-cpp-dev libboost-all-dev git libspdlog-dev
#             cmd_action: build_release
#           # - build_name: "Valgrind Build & Unit Tests"
#           #   cmd_deps: sudo apt-get install -y -qq valgrind libmbedtls-dev
#           #   cmd_action: unit_tests_valgrind MBEDTLS
#           # - build_name: "Clang Static Analyzer"
#           #   cmd_deps: sudo apt-get install -y -qq clang-11 clang-tools-11 libmbedtls-dev
#           #   cmd_action: build_clang_analyzer
#         os: [ubuntu-18.04, ubuntu-20.04]
#     name: ${{matrix.build_name}}
#     runs-on: ${{matrix.os}}
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         submodules: true
#     - name: Install Dependencies
#       run: |
#         sudo apt-get update
#         ${{ matrix.cmd_deps }}
#     - name: ${{matrix.build_name}}
#       uses: actions/build_linux.yaml@v1
#       with:
#         built_type: ${{matrix.cmd_action}}
