name: Linux Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include: 
          - build_name: "Release Build"
            cmd_deps: sudo apt-get install -y -qq libmbedtls-dev
            cmd_action: build_release
          - build_name: "Valgrind Build & Unit Tests"
            cmd_deps: sudo apt-get install -y -qq valgrind libmbedtls-dev
            cmd_action: unit_tests_valgrind MBEDTLS
          - build_name: "Clang Static Analyzer"
            cmd_deps: sudo apt-get install -y -qq clang-11 clang-tools-11 libmbedtls-dev
            cmd_action: build_clang_analyzer
        os: [ubuntu-18.04, ubuntu-20.04]
    name: ${{matrix.build_name}}
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        sudo apt-get update
        ${{ matrix.cmd_deps }}
    - name: ${{matrix.build_name}}
      uses: actions/build_linux.yaml@v1
      with:
        built_type: ${{matrix.cmd_action}}
