name: Linux Build

on: push #[push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y -qq libboost-python1.71.0 build-essential cmake libyaml-cpp-dev libboost-all-dev git libspdlog-dev
    - name: "Build open63541"
      uses: ./.github/actions/build_linux
      with:
        build-type: build_open62541
    - name: "Checkout Catch2"
      uses: actions/checkout@v2
      with:
        repository: catchorg/Catch2
        path: Catch2
        ref: v2.13.4
        submodules: true
    - name: "Build Catch2"
      uses: ./.github/actions/build_linux
      with:
        build-type: build_catch2
    - name: "Go back to this repository"
      run: |
        cd ${{ github.workspace }}
    - name: "Build Plugin Template"
      uses: ./.github/actions/build_linux
      with:
        build-type: build_release
    - run: |
        mkdir -p ./.github/actions_temp
        cp -R ./.github/actions/* ./.github/actions_temp
    - uses: actions/checkout@v2-beta
      with:
        repository: TW-Robotics/FHTW_Github_Actions
        ref: main
        token: ${{ secrets.SECRET_PAT_PRIVATE_DOWNLOAD }}
        path: .github/actions
    - run: |
        cp -R ./.github/actions_temp/* ./.github/actions
        tree -a -L 4
    - name: "Run the private Build_SAMYCore action"
      uses: ./.github/actions/build_SAMYCore_Linux
      with:
        catch2-exists: true
        open62541-exists: true
        secret-private-download: ${{ secrets.SECRET_PAT_PRIVATE_DOWNLOAD }}
    - name: "Upload the SAMYCore binary"
      uses: actions/upload-artifact@master
      with:
           name: SAMYCore
           path: SAMYCore/build/SAMYCore
    - name: "Upload the SAMYCore testsServer binary"
      uses: actions/upload-artifact@master
      with:
           name: SAMYCore-testsServer
           path: SAMYCore/build/testsServer
    - name: "Upload the cpp plugin test"
      uses: actions/upload-artifact@master
      with:
           name: SAMYPlugin-CPP-test
           path: SamyPlugins_Template_Cpp/build/test_robot
    - name: "Upload the testsClient binary"
      uses: actions/upload-artifact@master
      with:
           name: SAMYPlugin-testsClient
           path: SamyPlugins_Template_Cpp/build/testsClient
  test:
      runs-on: ubuntu-20.04
      needs: [build]
      steps:
      - run: |
             mkdir -p binaries && cd binaries
      - name: "Download the SAMYCore binary"
        uses: actions/download-artifact@master
        with:
            name: SAMYCore
            path: .
      - name: "Download the SAMYCore-testsServer binary"
        uses: actions/download-artifact@master
        with:
            name: SAMYCore-testsServer
            path: .
      - name: "Download the SAMYPlugin-CPP-test binary"
        uses: actions/download-artifact@master
        with:
            name: SAMYPlugin-CPP-test
            path: .
      - name: "Download the testsClient binary"
        uses: actions/download-artifact@master
        with:
            name: SAMYPlugin-testsClient
            path: .
      - run: |
             pwd
             ls
             tree -L 2
      - run: |
             sudo ./testsServer [ServerTest] &
      - run: |
             sudo ./testsClient







# name: Linux Build
#
# on: push #[push, pull_request]
# jobs:
#   build:
#     strategy:
#       fail-fast: false
#       matrix:
#         include:
#           - build_name: "Build open62541"
#             cmd_deps: sudo apt-get install -y -qq libboost-python1.71.0 build-essential cmake libyaml-cpp-dev libboost-all-dev git libspdlog-dev
#             cmd_action: build_open62541
#           - build_name: "Release Build"
#             cmd_deps: sudo apt-get install -y -qq libboost-python1.71.0 build-essential cmake libyaml-cpp-dev libboost-all-dev git libspdlog-dev
#             cmd_action: build_release
#           # - build_name: "Valgrind Build & Unit Tests"
#           #   cmd_deps: sudo apt-get install -y -qq valgrind libmbedtls-dev
#           #   cmd_action: unit_tests_valgrind MBEDTLS
#           # - build_name: "Clang Static Analyzer"
#           #   cmd_deps: sudo apt-get install -y -qq clang-11 clang-tools-11 libmbedtls-dev
#           #   cmd_action: build_clang_analyzer
#         os: [ubuntu-18.04, ubuntu-20.04]
#     name: ${{matrix.build_name}}
#     runs-on: ${{matrix.os}}
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         submodules: true
#     - name: Install Dependencies
#       run: |
#         sudo apt-get update
#         ${{ matrix.cmd_deps }}
#     - name: ${{matrix.build_name}}
#       uses: actions/build_linux.yaml@v1
#       with:
#         built_type: ${{matrix.cmd_action}}
